networks:
  walrus-net:
    external: true
    name: walrus-net

services:
  app:
    build: .
    environment:
      POSTGRES_DSN: "postgresql+psycopg2://walrus:walrus@localhost:55432/walrus"
      KAFKA_BOOTSTRAP: KAFKA_HOST:9092
      TOPIC_READY: data.ready
      TOPIC_DONE: compute.done
    ports:
      - "8081:8000"
    networks: [walrus-net]