networks:
  walrus-net:
    external: true
    name: walrus-net

services:
  app:
    build: .
    networks: [walrus-net]
    environment:
      POSTGRES_DSN: "postgresql+asyncpg://walrus:walrus@walrus-db:5432/walrus"
      KAFKA_BOOTSTRAP: 10.114.0.5:9092
      TOPIC_READY: input-topic
      TOPIC_DONE: calc.completed
    ports:
      - "8081:8000"