networks:
  walrus-net:
    external: true
    name: walrus-net

services:
  app:
    build: .
    environment:
      POSTGRES_DSN: postgresql+asyncpg://USER:PASS@POSTGRES_HOST:5432/DBNAME
      KAFKA_BOOTSTRAP: KAFKA_HOST:9092
      TOPIC_READY: data.ready
      TOPIC_DONE: compute.done
    ports:
      - "8081:8000"
    networks: [external_net]